config/routes.rb
Rails.application.routes.draw do
  root to: "top#index"
  devise_for :users
  resources :units, only: [:index, :new, :create, :edit, :update] do
    resources :home, only: [:index]
  end

  resources :messages, only: [:create, :edit, :update, :destroy]
  resources :tasks, only: [:create, :edit, :update]
  resources :search, only: [:index]

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/event_date.rb
class EventDate < ApplicationRecord
  has_many :messages
  has_many :tasks
end

app/models/message.rb
class Message < ApplicationRecord
  validates :text, presence: { message: '申し送りを入力してください' }
  validates :name, presence: { message: '名前を入力してください' }

  belongs_to :unit
  belongs_to :event_date
  has_one_attached :image
end

app/models/task.rb
class Task < ApplicationRecord
  validates :text, presence: { message: 'タスクを入力してください' }
  validates :name, presence: { message: '名前を入力してください' }
  validates :due_date, presence: { message: '期限を入力してください' }
  validates :completed, inclusion: { in: [true, false] }

  belongs_to :unit
  belongs_to :event_date
end

app/models/unit.rb
class Unit < ApplicationRecord
validates :name, presence: true

belongs_to :user
has_many :messages
has_many :tasks
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  validates :name, presence: true
  
  has_many :units
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :basic_auth
  before_action :authenticate_user!, unless: :top_page?
  before_action :configure_permitted_parameters, if: :devise_controller?

  private

  def top_page?
    controller_name == 'top' && action_name == 'index'
  end

  def basic_auth
    authenticate_or_request_with_http_basic do |username, password|
      username == ENV["BASIC_AUTH_USER"] && password == ENV["BASIC_AUTH_PASSWORD"]
    end
  end

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end

  def after_sign_in_path_for(resource)
    units_path
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :unit_same_user

  def index
    # 階層に結びつくhomeを表示する
    @unit = Unit.find_by(id: params[:unit_id])
    if @unit == nil
      # redirect_to LPページ and return
    end
    
    # 日付機能
    if params['event_date(1i)'].present? && params['event_date(2i)'].present?
      year = params['event_date(1i)'].to_i
      month = params['event_date(2i)'].to_i
    elsif params[:date]
      date = Date.parse(params[:date])
      year = date.year
      month = date.month
    else
      year = Date.today.year
      month = Date.today.month
    end
    start_date = Date.new(year, month, 1)
    end_date = start_date.end_of_month
    @event_date = EventDate.where(event_date: start_date..end_date)
    
    # 申し送り機能
    @message = Message.new
    today = Date.today 
    @today_date = EventDate.find_by(event_date: today)
    @unit_id = params[:unit_id]
    if params[:date]
      @date = Date.parse(params[:date])
      @messages = Message.where(created_at: @date.beginning_of_day..@date.end_of_day)
    else
      @messages = Message.where(event_date_id: @today_date.id, unit_id: params[:unit_id])
    end
    

    # タスク機能
    @task = Task.new
    today = Date.today 
    @today_dates = EventDate.where(event_date: today)
    @non_completed = Task.where(unit_id: params[:unit_id], completed: 0)
    @completed = Task.where(event_date_id: @today_dates, unit_id: params[:unit_id], completed: 1)
  end

  private
  def unit_same_user
    unit = Unit.find(params[:unit_id])
    unless current_user.id == unit.user_id
      redirect_to units_path
    end
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :same_action, only: [:edit, :update, :destroy, :message_ownership]
  before_action :message_ownership, only: [:edit, :update, :delete]

  def create
    @unit = Unit.find_by(id: params[:message][:unit_id])
    @message = Message.new(message_params)
    if @message.save
      redirect_to unit_home_index_path(unit_id: @message.unit_id)
    else
      flash[:message_error] = @message.errors.full_messages
      redirect_to unit_home_index_path(unit_id: @message.unit_id)
    end
  end

  def edit
    
    @unit = @message.unit
  end

  def update
    
    if @message.update(message_params)
      redirect_to unit_home_index_path(unit_id: @message.unit_id)
    else
      render :edit
    end
  end

  def destroy
    

    unit_id = @message.unit_id
    if @message.destroy
      redirect_to unit_home_index_path(unit_id: unit_id)
    else
      render 'home#index'
    end
  end
  
  private

  def message_params
    event_date = EventDate.find_by(event_date: params[:message][:event_date])
    params[:message][:event_date_id] = event_date.id if event_date
    params.require(:message).permit(:text,:name,:unit_id, :event_date_id, :image)
  end

  def same_action
    @message = Message.find_by(id: params[:id])
    @unit = @message.unit
  end

  def message_ownership

    
    if @unit && @unit.user_id != current_user.id
      redirect_to units_path(@unit)
    end
  end
end

app/controllers/search_controller.rb
class SearchController < ApplicationController
  def index
    user_units = Unit.where(user_id: current_user.id).pluck(:id)
    if params[:q].present?
      @messages_search = Message.where(unit_id: user_units).ransack(name_or_text_cont: params[:q]).result
      render json:{ messages_search: @messages_search }

    else
      @messages_search = []
      @tasks_search = []
    end
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :task_ownership,only: [:edit, :update]
  
  def create
    @unit = Unit.find_by(id: params[:task][:unit_id])
    @task = Task.new(task_params)
    
    if @task.save
      redirect_to unit_home_index_path(unit_id: @task.unit_id)
    else
      flash[:task_error] = @task.errors.full_messages
      redirect_to unit_home_index_path(unit_id: @task.unit_id)
    end
  end

  def edit
    today = Date.today 
    @today_date = EventDate.find_by(event_date: today)
    @task = Task.find(params[:id])
    @unit = @task.unit
  end
  
  def update
    @task = Task.find(params[:id])
    if @task.update(task_params)
      if params[:is_ajax] == 'true'
        render json: { task: @task }
      else
        redirect_to unit_home_index_path(unit_id: @task.unit_id)
      end
    else
      render :edit
    end
  end

  private
  def task_params
    event_date = EventDate.find_by(event_date: params[:task][:event_date])
    params[:task][:event_date_id] = event_date.id if event_date
    params[:task][:completed] = params[:task][:completed] == '1'
    params.require(:task).permit(:text,:name,:unit_id, :event_date_id, :due_date, :completed)
  end

  def task_ownership
    @task = Task.find(params[:id])
    @unit = @task.unit
    
    if @unit && @unit.user_id != current_user.id
      redirect_to units_path(@unit)
    end
  end
end

app/controllers/top_controller.rb
class TopController < ApplicationController
  def index
  end
end

app/controllers/units_controller.rb
class UnitsController < ApplicationController
  before_action :check_ownership, only: [:edit]

  def index
    @units = Unit.where(user_id: current_user.id)
  end

  def new
   @unit = Unit.new
  end

  def create
    @unit = Unit.new(unit_params)

    if @unit.save
      redirect_to units_path
    else
      render :new
    end
  end

  def show
    @unit = Unit.find(params[:id])
  end

  def edit
    @unit = Unit.find(params[:id])
  end

   def update
    unit = Unit.find(params[:id])
    if unit.update(unit_params)
      redirect_to units_path
    else
      render :edit
    end
   end

  private

  def unit_params
    params.require(:unit).permit(:name).merge(user_id: current_user.id)
  end

  def check_ownership
    unit = Unit.find(params[:id])
    if current_user.id != unit.user_id
      redirect_to root_path
    end
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/helpers/top_helper.rb
module TopHelper
end

app/helpers/units_helper.rb
module UnitsHelper
end

app/views/home/index.html.erb
<header>
  <div class="home-header">
    <%= link_to image_tag('taskyrelay.jpg', class: "logo"), root_path %>
    <div class="search-content">
      <%= form_with url: search_index_path, method: :get, local: true, id:"form", class:"search-form"  do |f| %>
        <%= f.text_field :q, placeholder: '申し送りの検索' %>
        <%= f.submit "検索", id:"submit" %>
      <% end %>
      <div id="wrapper-container">
        <div id="searchResultOverlay" class="overlay">
          <div id="searchResultTable" class="result-table"></div>
        </div>
      </div>
    </div>
    <div class="header-content">
      <h1 class="corp-link">
        <%= link_to current_user.name, units_path %>
      </h1>
      <h1 class="corp-name">
        <%= @unit.name %>
      </h1>
    </div>
  </div>
</header>

<div class="main-content">
  <div class="home-date">

    <%= form_with url: unit_home_index_path(@unit), method: :get, local: true, class: "date-search" do |f| %>
        <%= f.date_select :event_date, discard_day: true %>
        <div>
          <%= f.submit '検索', class: "date-btn" %>
        </div>
        
      <% end %>
    <div class="date-content">
      <% @event_date.each do |ed| %>
        <div class="date-font">
          <%= link_to ed.event_date.strftime("%Y年  %-m月  %d日"),  controller: :home, action: :index, date: ed.event_date, unit_id: @unit_id %>
        </div>
      <% end %>
    </div>
  </div>

  <div class="home-message">
      <%= form_with model: @message, url: messages_path, local: true, scope: :message do |f| %>
        <% if flash[:message_error] %>
          <div class="error-alert">
            <ul>
              <% flash[:message_error].each do |message| %>
                <li class='error-message'><%= message %></li>
              <% end %>
            </ul>
          </div>
        <% end %>
        <div class="message-form-content">
          <div class="message-form-left">
            <div class="message-form">
              <%= f.text_area :text, placeholder: "申し送り" %>
            </div>
            <div>
              <%= f.text_field :name, placeholder: "名前" %>
            </div>
          </div>
          <div class="message-form-right">
            <div class="message-date">
              <%= f.hidden_field :event_date, value: @today_date.event_date %>
            </div>
            <div class="message-form">
              <%= f.file_field :image %>
            </div>
            <%= f.hidden_field :unit_id, value: @unit.id %>
            <%= f.submit "保存", class: "message-btn" %>
          </div>
        </div>
      <% end %>

      <div class="message-content">
        <% @messages.each do |message| %>
          <div class="moushiokuri">
            <div class="moushiokuri-title">
              <div><%= @date ? @date.strftime("%m/%d") : @today_date.event_date.strftime("%m/%d") %>  申し送り</div>
            </div>
            <div class="moushiokuri-text">
              <%= message.text %>
            </div>
            <div class="moushiokuri-image">
              <%= image_tag url_for(message.image), class: "message-image" if message.image.attached? %>
            </div>
            <div class="moushiokuri-under">
              <%= message.name %>
              <%= message.created_at.in_time_zone('Tokyo').strftime("%H:%M") %>
              <%= link_to "編集", edit_message_path(message), class: "moushiokuri-link" %>
              <%= link_to "削除", message_path(message), method: :delete, class: "moushiokuri-link" %>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  <div class="home-task">
    <%= form_with model: @task, url: tasks_path, local: true, scope: :task do |f| %>
        <% if flash[:task_error] %>
          <div class="error-alert">
            <ul>
              <% flash[:task_error].each do |message| %>
                <li class='error-message'><%= message %></li>
              <% end %>
            </ul>
          </div>
        <% end %>
        

        <div class="task-form-content">
          <div class="task-form-left">
            <div class="task-form">
              <%= f.text_area :text, placeholder: "タスク" %>
            </div>
            <div>
              <%= f.text_field :name, placeholder: "名前" %>
            </div>
          </div>
          <div class="task-form-right">
            <div class="task-date">期限：
              <%= f.datetime_local_field :due_date %>
            </div>
            <%= f.hidden_field :completed, value: false %>
            <%= f.hidden_field :event_date, value: @today_date.event_date %>
            <%= f.hidden_field :unit_id, value: @unit.id %>
            <%= f.submit "保存", class: "task-btn" %>
          </div>
        </div>
    <% end %>

    <div class="task-content">
      <div id="non-comp">
        <div class="comp-title">未完了</div>
        <% @non_completed.each do |task| %>
          <div class="not-comp" id="task-<%= task.id %>">
            <div class="task-text"><%= task.text %></div>
            <div class="task-under">
              <%= task.name %>
              期限：<%= task.due_date.strftime("%-m/%d  %H:%M") %>
              <%= form_with model: task, scope: :task, url: task_path(task), id: "form-#{task.id}" do |f| %>
                <%= f.check_box :completed, id: "check-#{task.id}" %>
              <% end %>
              <%= link_to "編集", edit_task_path(task), class: "moushiokuri-link"  %>
            </div>
          </div>
        <% end %>
      </div>
      <div id="comp">
        <div class="comp-title">完了済み</div>
        <% @completed.each do |task| %>
          <div class="complete" id="task-<%= task.id %>">
            <div class="task-text"><%= task.text %></div>
            <div class="task-under">
              <%= task.name %>
              期限：<%= task.due_date.strftime("%-m/%d  %H:%M") %>
              <%= form_with model: task, scope: :task, url: task_path(task), id: "form-#{task.id}" do |f| %>
                <%= f.check_box :completed, id: "check-#{task.id}" %>
              <% end %>
              <%= link_to "編集", edit_task_path(task), class: "moushiokuri-link"  %>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

<div id="wrapper-container">
  <div id="searchResultOverlay" class="overlay">
    <div id="searchResultTable" class="result-table"></div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TaskyRelay</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/normalize/8.0.1/normalize.css">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Zen+Kurenaido&display=swap" rel="stylesheet">

  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/messages/edit.html.erb
<%= render 'shared/header' %>


<div class="message-edit-content">
  <div class="meesage-edit">
    <%= form_with model: @message, local: true, scope: :message do |f| %>
      <%= render 'shared/error_messages', resource: @message %>
      <div class="message-form-content">
        <div class="message-form-left">
          <div class="message-form">
            <%= f.text_area :text, placeholder: "内容" %>
          </div>
          <div>
            <%= f.text_field :name, placeholder: "名前" %>
          </div>
        </div>
        <div class="message-form-right">
          <div class="message-date">
            <div class="message-edit-date">申し送りの日付を変更する</div>
            <%= f.date_field :event_date %>
          </div>
          <div class="message-form">
            <%= f.file_field :image %>
          </div>
          <%= f.hidden_field :unit_id, value: @unit.id %>
          <%= f.submit "保存", class: "message-btn" %>
      </div>
      </div>
    <% end %>
  </div>
</div>

app/views/shared/_error_messages.html.erb
<% if resource.errors.any? %>
<div class="error-alert">
  <ul>
    <% resource.errors.full_messages.each do |message| %>
    <li class='error-message'><%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>

app/views/shared/_header.html.erb
<header>
  <div class="home-header">
    <%= link_to image_tag('taskyrelay.jpg', class: "logo"), root_path %>
    <div class="top-header">
      <% if user_signed_in? %>
        <div class="left-header-name"><%= link_to current_user.name, units_path %></div>
        <div class="right-header"><%= link_to "ログアウト", destroy_user_session_path, method: :delete  %></div>
      <% else %>
        <div class="left-header"><%= link_to "ログイン", new_user_session_path %></div>
        <div class="right-header"><%= link_to "新規登録はこちらから", new_user_registration_path %></div>
      <% end %>
    </div>
  </div>
</header>

app/views/tasks/edit.html.erb
<%= render 'shared/header' %>


<%= form_with model: @task, url: task_path(@task), local: true, scope: :task do |f| %>

<%= render 'shared/error_messages', resource: @task %>

<div class="edit-task-form-content">
  <div class="task-form-content">
    <div class="task-form-left">
      <div class="task-form">
        <%= f.text_area :text, placeholder: "タスク" %>
      </div>
      <div>
        <%= f.text_field :name, placeholder: "名前" %>
      </div>
    </div>
    <div class="task-form-right">
      <div class="task-date">期限：
        <%= f.datetime_local_field :due_date %>
      </div>
      <%= f.hidden_field :event_date, value: @today_date.event_date %>
      <%= f.hidden_field :unit_id, value: @unit.id %>
      <%= f.submit "保存", class: "edit-task-btn" %>
    </div>
  </div>
</div>
<% end %>

app/views/top/index.html.erb
<%= render 'shared/header' %>

<div class="top-content">
  <div class="kaigo">
    <%= image_tag 'top-image.jpg', class: "kaigo-image" %>
    <div class="kaigo-items">
      <div class="kaigo-text">
        <div class="kaigo-text-main">TaskyRelayは、<br>介護業界向けの新しいタスク管理と申し送りアプリ</div>
        <div class="kaigo-text-sub">タスクと申し送り、一緒に管理。</div>
        <div class="kaigo-text-subsub">タスキーリレーは、介護職員のための日々のタスクと申し送りを一元化して管理するのをお手伝いをします。</div>
      </div>
    </div>
  </div>

  <div class="mid-con">
    <div class="circle-orange"></div>
      <div class="mid-con-items">
        <div class="kaigo-text">
          <div class="kaigo-text-main">特徴</div>
          <div class="kaigo-text-list">1. 日付ごとのタスクと申し送りの一元管理</div>
          <div class="kaigo-text-subsub">カレンダーに結びついた形式で、日々のタスクと申し送りを一覧表示。忙しい毎日でも、仕事をスムーズに進めることが可能です。</div>
          <div class="kaigo-text-list">2. 申し送りとタスク管理、一緒に表示</div>
          <div class="kaigo-text-subsub">申し送りとタスクが同一の画面に。複数の画面を行き来することなく、一目で全ての情報を確認できます。</div>
        </div>
    </div>
  </div>

  <div class="mid-bot-con">
    <div class="circle"></div>
      <div class="mid-bot-con-items">
        <div class="kaigo-text">
          <div class="kaigo-text-list">タスキーリレーが解決します。</div>
          <div class="kaigo-text-subsub">業務に追われタスクを忘れることはありません。日々のタスクを確認・管理することができます。</div>
        </div>
    </div>
  </div>

  <div class="bot-content">
      <div class="bot-link">
        <%= link_to '利用開始！', units_path, class: "square" %>
      </div>
  </div>

  <footer>
    <div>
      さぁ、タスキーリレーと一緒に安心、安全なケアを提供しましょう。
    </div>
  </footer>

</div>

app/views/units/edit.html.erb
<%= render 'shared/header' %>
<div class="unit-edit">
  <h1>階層もしくはユニット名を編集する</h1>

  <%= form_with model: @unit, local: true do |f| %>
  
  <%= render 'shared/error_messages', resource: @unit %>
  
    <div class="field">
  
      <%= f.text_field :name, class: "form-control", placeholder: @unit.name %>
    </div>
  
    <div class="actions">
      <%= f.submit "編集", class: "btn" %>
    </div>
  <% end %>
</div>

app/views/units/index.html.erb
<%= render 'shared/header' %>

<div class="unit-content">
  <% @units.each do |unit| %>
  <div class="unit">
    <div class="unit-back">
      <div class="unit-name">
        <div class="unit-left">
          <%= link_to unit.name, unit_home_index_path(unit), class: "unit-link" %>
        </div>
        <div class="unit-right">
          <%= link_to "編集する", edit_unit_path(unit), class: "unit-link" %>
        </div>
      </div>
    </div>
  </div>
  <% end %>
</div>


<div class="bottom-link">
  <%= link_to "階層もしくはユニットを新規作成 ", new_unit_path, class: "link" %>
</div>

app/views/units/new.html.erb
<%= render 'shared/header' %>

<div class="unit-new">
  <h1>階層もしくはユニット名を新規作成</h1>

<%= form_with model: @unit, local: true do |f| %>

<%= render 'shared/error_messages', resource: @unit %>

  <div class="field">
    <%= f.text_field :name, class: "form-control" %>
  </div>

  <div class="actions">
    <%= f.submit "作成する", class: "btn" %>
  </div>
<% end %>
</div>